In [44]:
# Import libraries
import pandas as pd 
import numpy as np

In [45]:
# Import data
df = pd.read_csv("E:/Users/FIZZ/Documents/@Hamoye/Building FAO Dashboard/Data/FoodBalanceSheets_E_Africa/FoodBalanceSheets_E_Africa_NOFLAG.csv")

In [46]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,35977.00,36661.00,37384.00,38140.00,38924.00,39728.00,40551.00,41389.00,42228.00,43053.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3250.00,3350.00,3366.00,3436.00,3424.00,3417.00,3443.00,3383.00,3382.00,3493.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,87.27,88.77,91.26,90.89,91.06,91.24,90.14,88.64,90.29,90.84
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,84.53,93.82,88.10,97.71,97.59,93.83,101.03,97.12,87.27,98.14

In [47]:
# shape and data types of the data
print(df.shape)
print(df.dtypes)

(91446, 17)
Area Code         int64
Area             object
Item Code         int64
Item             object
Element Code      int64
Element          object
Unit             object
Y2010           float64
Y2011           float64
Y2012           float64
Y2013           float64
Y2014           float64
Y2015           float64
Y2016           float64
Y2017           float64
Y2018           float64
Y2019           float64
dtype: object

In [48]:
# select numeric columns
df_numeric = df.select_dtypes(include=[np.number])
numeric_cols = df_numeric.columns.values
print(numeric_cols)

['Area Code' 'Item Code' 'Element Code' 'Y2010' 'Y2011' 'Y2012' 'Y2013'
 'Y2014' 'Y2015' 'Y2016' 'Y2017' 'Y2018' 'Y2019']

In [49]:
# select non numeric columns
df_non_numeric = df.select_dtypes(exclude=[np.number])
non_numeric_cols = df_non_numeric.columns.values
print(non_numeric_cols)

['Area' 'Item' 'Element' 'Unit']

In [50]:
# Count the number of null values in the dataset
df.isnull().sum()

Area Code           0
Area                0
Item Code           0
Item                0
Element Code        0
Element             0
Unit                0
Y2010           29045
Y2011           29031
Y2012           27723
Y2013           27927
Y2014           27646
Y2015           27562
Y2016           27646
Y2017           27451
Y2018           27302
Y2019           27374
dtype: int64

In [51]:
# Percentage of missing dataset.
for col in df.columns:
    pct_missing = np.mean(df[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

Area Code - 0%
Area - 0%
Item Code - 0%
Item - 0%
Element Code - 0%
Element - 0%
Unit - 0%
Y2010 - 32%
Y2011 - 32%
Y2012 - 30%
Y2013 - 31%
Y2014 - 30%
Y2015 - 30%
Y2016 - 30%
Y2017 - 30%
Y2018 - 30%
Y2019 - 30%

In [52]:
# Count number of zeros in all columns of Dataframe
for column_name in df.columns:
    column = df[column_name]
    # Get the count of Zeros in column 
    count = (column == 0).sum()
    print('Count of zeros in column ', column_name, ' is : ', count)

Count of zeros in column  Area Code  is :  0
Count of zeros in column  Area  is :  0
Count of zeros in column  Item Code  is :  0
Count of zeros in column  Item  is :  0
Count of zeros in column  Element Code  is :  0
Count of zeros in column  Element  is :  0
Count of zeros in column  Unit  is :  0
Count of zeros in column  Y2010  is :  28599
Count of zeros in column  Y2011  is :  28405
Count of zeros in column  Y2012  is :  28557
Count of zeros in column  Y2013  is :  27984
Count of zeros in column  Y2014  is :  27005
Count of zeros in column  Y2015  is :  27278
Count of zeros in column  Y2016  is :  27205
Count of zeros in column  Y2017  is :  27220
Count of zeros in column  Y2018  is :  27493
Count of zeros in column  Y2019  is :  27407

In [62]:
#Drop null values
df1 = df.dropna(axis = 0)

df1.to_csv("Cleaned_data.csv")

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [63]:
df2 = pd.read_csv('Cleaned_data.csv')

In [66]:
df2.head(50)

,Unnamed: 0,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,35977.00,36661.00,37384.00,38140.00,38924.00,39728.00,40551.00,41389.00,42228.00,43053.00
1,1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3250.00,3350.00,3366.00,3436.00,3424.00,3417.00,3443.00,3383.00,3382.00,3493.00
3,3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,87.27,88.77,91.26,90.89,91.06,91.24,90.14,88.64,90.29,90.84
4,4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,84.53,93.82,88.10,97.71,97.59,93.83,101.03,97.12,87.27,98.14
5,5,4,Algeria,2903,Vegetal Products,664,Food supply (kcal/capita/day),kcal/capita/day,2866.00,2941.00,2951.00,3018.00,2989.00,3002.00,3019.00,2974.00,3000.00,3114.00
6,6,4,Algeria,2903,Vegetal Products,674,Protein supply quantity (g/capita/day),g/capita/day,63.25,63.39,64.99,64.43,63.75,64.58,63.18,62.72,65.99,66.76
7,7,4,Algeria,2903,Vegetal Products,684,Fat supply quantity (g/capita/day),g/capita/day,61.62,69.36,63.71,73.23,71.85,69.53,76.02,73.17,65.04,76.00
8,8,4,Algeria,2941,Animal Products,664,Food supply (kcal/capita/day),kcal/capita/day,384.00,409.00,415.00,418.00,436.00,415.00,424.00,409.00,382.00,379.00
9,9,4,Algeria,2941,Animal Products,674,Protein supply quantity (g/capita/day),g/capita/day,24.02,25.38,26.26,26.45,27.31,26.67,26.95,25.92,24.30,24.09
10,10,4,Algeria,2941,Animal Products,684,Fat supply quantity (g/capita/day),g/capita/day,22.91,24.46,24.39,24.48,25.74,24.30,25.01,23.95,22.23,22.14
11,11,4,Algeria,2905,Cereals - Excluding Beer,5511,Production,1000 tonnes,4211.00,4248.00,5137.00,4913.00,3436.00,3761.00,3445.00,3478.00,6065.00,5634.00
12,12,4,Algeria,2905,Cereals - Excluding Beer,5611,Import Quantity,1000 tonnes,8066.00,11213.00,10058.00,10332.00,12604.00,13983.00,13523.00,13039.00,13219.00,11527.00
13,13,4,Algeria,2905,Cereals - Excluding Beer,5072,Stock Variation,1000 tonnes,-1254.00,628.00,-57.00,-40.00,562.00,994.00,106.00,153.00,794.00,193.00
14,14,4,Algeria,2905,Cereals - Excluding Beer,5911,Export Quantity,1000 tonnes,10.00,5.00,5.00,2.00,3.00,7.00,7.00,10.00,3.00,5.00
15,15,4,Algeria,2905,Cereals - Excluding Beer,5301,Domestic supply quantity,1000 tonnes,13521.00,14828.00,15247.00,15282.00,15475.00,16744.00,16855.00,16355.00,18487.00,16963.00
16,16,4,Algeria,2905,Cereals - Excluding Beer,5521,Feed,1000 tonnes,3614.00,4194.00,4320.00,4461.00,4879.00,5246.00,5036.00,4845.00,5460.00,5209.00
17,17,4,Algeria,2905,Cereals - Excluding Beer,5527,Seed,1000 tonnes,225.00,225.00,273.00,261.00,181.00,198.00,182.00,183.00,322.00,298.00
18,18,4,Algeria,2905,Cereals - Excluding Beer,5123,Losses,1000 tonnes,795.00,1011.00,980.00,975.00,1064.00,1143.00,1127.00,1103.00,1253.00,1132.00
19,19,4,Algeria,2905,Cereals - Excluding Beer,5131,Processing,1000 tonnes,25.00,25.00,26.00,26.00,35.00,38.00,37.00,33.00,40.00,40.00
20,20,4,Algeria,2905,Cereals - Excluding Beer,5154,Other uses (non-food),1000 tonnes,1279.00,1730.00,1632.00,1603.00,1279.00,1830.00,2208.00,1831.00,2331.00,1086.00
21,22,4,Algeria,2905,Cereals - Excluding Beer,5170,Residuals,1000 tonnes,0.00,-1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
22,23,4,Algeria,2905,Cereals - Excluding Beer,5142,Food,1000 tonnes,7583.00,7645.00,8016.00,7956.00,8038.00,8289.00,8266.00,8360.00,9080.00,9198.00
23,24,4,Algeria,2905,Cereals - Excluding Beer,645,Food supply quantity (kg/capita/yr),kg,210.78,208.53,214.43,208.61,206.51,208.64,203.84,201.99,215.03,213.64
24,25,4,Algeria,2905,Cereals - Excluding Beer,664,Food supply (kcal/capita/day),kcal/capita/day,1614.00,1597.00,1641.00,1597.00,1581.00,1598.00,1560.00,1549.00,1645.00,1637.00
25,26,4,Algeria,2905,Cereals - Excluding Beer,674,Protein supply quantity (g/capita/day),g/capita/day,47.58,47.07,48.30,46.97,46.41,46.94,45.81,45.62,48.46,48.27
26,27,4,Algeria,2905,Cereals - Excluding Beer,684,Fat supply quantity (g/capita/day),g/capita/day,6.33,6.36,6.53,6.41,6.51,6.53,6.33,6.25,6.47,6.47
27,28,4,Algeria,2511,Wheat and products,5511,Production,1000 tonnes,2605.00,2911.00,3432.00,3299.00,2436.00,2657.00,2440.00,2437.00,3981.00,3877.00
28,29,4,Algeria,2511,Wheat and products,5611,Import Quantity,1000 tonnes,5109.00,7487.00,6385.00,6343.00,7462.00,8531.00,8255.00,8105.00,8434.00,6788.00
29,30,4,Algeria,2511,Wheat and products,5072,Stock Variation,1000 tonnes,-1238.00,647.00,-51.00,-81.00,502.00,897.00,52.00,101.00,701.00,151.00
30,31,4,Algeria,2511,Wheat and products,5911,Export Quantity,1000 tonnes,9.00,5.00,5.00,2.00,3.00,7.00,6.00,10.00,2.00,4.00
31,32,4,Algeria,2511,Wheat and products,5301,Domestic supply quantity,1000 tonnes,8942.00,9746.00,9863.00,9721.00,9393.00,10284.00,10637.00,10431.00,11712.00,10510.00
32,33,4,Algeria,2511,Wheat and products,5521,Feed,1000 tonnes,460.00,623.00,588.00,577.00,562.00,617.00,638.00,626.00,703.00,631.00
33,34,4,Algeria,2511,Wheat and products,5527,Seed,1000 tonnes,131.00,147.00,173.00,166.00,123.00,134.00,123.00,123.00,201.00,195.00
34,35,4,Algeria,2511,Wheat and products,5123,Losses,1000 tonnes,536.00,726.00,685.00,672.00,690.00,781.00,747.00,736.00,868.00,746.00
35,37,4,Algeria,2511,Wheat and products,5154,Other uses (non-food),1000 tonnes,1279.00,1730.00,1632.00,1603.00,1279.00,1830.00,2208.00,1831.00,2331.00,1086.00
36,39,4,Algeria,2511,Wheat and products,5170,Residuals,1000 tonnes,0.00,-1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
37,40,4,Algeria,2511,Wheat and products,5142,Food,1000 tonnes,6535.00,6522.00,6786.00,6703.00,6740.00,6923.00,6921.00,7115.00,7609.00,7852.00
38,41,4,Algeria,2511,Wheat and products,645,Food supply quantity (kg/capita/yr),kg,181.65,177.91,181.52,175.75,173.16,174.25,170.68,171.91,180.19,182.38
39,42,4,Algeria,2511,Wheat and products,664,Food supply (kcal/capita/day),kcal/capita/day,1395.00,1366.00,1394.00,1350.00,1330.00,1338.00,1311.00,1322.00,1385.00,1401.00
40,43,4,Algeria,2511,Wheat and products,674,Protein supply quantity (g/capita/day),g/capita/day,42.11,41.24,42.07,40.72,40.12,40.40,39.56,39.89,41.82,42.33
41,44,4,Algeria,2511,Wheat and products,684,Fat supply quantity (g/capita/day),g/capita/day,5.17,5.06,5.22,5.08,5.02,4.96,4.87,4.86,5.00,5.06
42,45,4,Algeria,2807,Rice and products,5511,Production,1000 tonnes,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
43,46,4,Algeria,2807,Rice and products,5611,Import Quantity,1000 tonnes,152.00,125.00,159.00,176.00,171.00,164.00,162.00,190.00,217.00,187.00
44,47,4,Algeria,2807,Rice and products,5072,Stock Variation,1000 tonnes,11.00,-19.00,3.00,31.00,17.00,9.00,6.00,28.00,58.00,25.00
45,49,4,Algeria,2807,Rice and products,5301,Domestic supply quantity,1000 tonnes,142.00,144.00,156.00,145.00,154.00,156.00,157.00,163.00,160.00,162.00
46,50,4,Algeria,2807,Rice and products,5521,Feed,1000 tonnes,1.00,6.00,3.00,2.00,5.00,1.00,1.00,2.00,0.00,0.00
47,51,4,Algeria,2807,Rice and products,5527,Seed,1000 tonnes,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
48,52,4,Algeria,2807,Rice and products,5123,Losses,1000 tonnes,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
49,56,4,Algeria,2807,Rice and products,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [73]:
print(df2.shape)

(57869, 18)

In [75]:
# Remove rows with all 0s in a Dataframe
df3 = df2.drop(df2.index[df2['Y2010','Y2011','Y2012','Y2013','Y2014','Y2015','Y2016','Y2017','Y2018','Y2019'] == 0])
print(df3)

KeyError: ('Y2010', 'Y2011', 'Y2012', 'Y2013', 'Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018', 'Y2019')